const mongoose = require("mongoose");

const Schema = mongoose.Schema;

const grantSchema = new Schema(
  {
    userId:                 { type: String, required: false },
    grantStatus:            { type: String, required: false },

    benTitle:               { type: String, required: false },
    benFirstName:           { type: String, required: false },
    benLastName:            { type: String, required: false },
    benEmail:               { type: String, required: false },
    benTelephone:           { type: String, required: false },

    benAbode:               { type: String, required: false },
    benAddressLine1:        { type: String, required: false },
    benAddressLine2:        { type: String, required: false },
    benTown:                { type: String, required: false },

    altTitle:               { type: String, required: false },
    altFirstName:           { type: String, required: false },
    altLastName:            { type: String, required: false },
    altRole:                { type: String, required: false },
    altEmail:               { type: String, required: false },
    altTelephone:           { type: String, required: false },
    altAddressLine1:        { type: String, required: false },
    altAddressLine2:        { type: String, required: false },
    altCounty:              { type: String, required: false },
    altPostcode:            { type: String, required: false },

    sharedSignedLink:       { type: String, required: false },
    prefContactMethod:      { type: String, required: false },
    prefCommunication:      { type: String, required: false },
    prefDataSharing:        { type: String, required: false },

    benAgeRange:            { type: String, required: false },
    benDob:                 { type: String, required: false },
    benGen:                 { type: String, required: false },
    benSex:                 { type: String, required: false },
    benEthnicity:           { type: String, required: false },
    benReligion:            { type: String, required: false },

    benDisability:          { type: String, required: false },
    benDisabilityExtra:     { type: String, required: false },

    benMarital:             { type: String, required: false },
    benDependants:          { type: String, required: false },
    benPregnancy:           { type: String, required: false },
    numOfDependants:        { type: String, required: false },
    ageOfDependants:        { type: String, required: false },
    dependantInformation:   { type: String, required: false },

    currentAccom:           { type: String, required: false },
    benCurrentAccomLength:  { type: String, required: false },
    benHistOfHomelessness:  { type: String, required: false },
    benHistDetails:         { type: String, required: false },
    benTimeInNottingham:    { type: String, required: false },
    benLinktoNottingham:    { type: String, required: false },
    benLinkDetails:         { type: String, required: false },

    benGrantReason:         { type: String, required: false },
    grantDetails:           { type: String, required: false },
    benStory:               { type: String, required: false },

    grantAmountTotal:       { type: String, required: false },
    grantItemCost1:         { type: String, required: false },
    grantItemDetails1:      { type: String, required: false },
    grantItemCost2:         { type: String, required: false },
    grantItemDetails2:      { type: String, required: false },
    grantItemCost3:         { type: String, required: false },
    grantItemDetails3:      { type: String, required: false },
    grantItemCost4:         { type: String, required: false },
    grantItemDetails4:      { type: String, required: false },
    grantItemCost5:         { type: String, required: false },
    grantItemDetails5:      { type: String, required: false },
    
    grantQuoteLink:         { type: String, required: false },
    submissionDate:         { type: String, required: false },
  },
  { timestamps: false }
);

//static signup method
grantSchema.statics.applyGrant = async function (
  userId,
  grantStatus,
  benTitle,
  benFirstName,
  benLastName,
  benEmail,
  benTelephone,
  benAbode,
  benAddressLine1,
  benAddressLine2,
  benTown,
  altTitle,
  altFirstName,
  altLastName,
  altRole,
  altEmail,
  altTelephone,
  altAddressLine1,
  altAddressLine2,
  altCounty,
  altPostcode,
  sharedSignedLink,
  prefContactMethod,
  prefCommunication,
  prefDataSharing,
  benAgeRange,
  benDob,
  benGen,
  benSex,
  benEthnicity,
  benReligion,
  benDisability,
  benDisabilityExtra,
  benMarital,
  benDependants,
  benPregnancy,
  numOfDependants,
  ageOfDependants,
  dependantInformation,
  currentAccom,
  benCurrentAccomLength,
  benHistOfHomelessness,
  benHistDetails,
  benTimeInNottingham,
  benLinktoNottingham,
  benLinkDetails,
  benGrantReason,
  grantDetails,
  benStory,
  grantAmountTotal,
  grantItemCost1,
  grantItemDetails1,
  grantItemCost2,
  grantItemDetails2,
  grantItemCost3,
  grantItemDetails3,
  grantItemCost4,
  grantItemDetails4,
  grantItemCost5,
  grantItemDetails5,
  grantQuoteLink,
  submissionDate
) {
  const grant = await this.create({
    userId,
    grantStatus,
    benTitle,
    benFirstName,
    benLastName,
    benEmail,
    benTelephone,
    benAbode,
    benAddressLine1,
    benAddressLine2,
    benTown,
    altTitle,
    altFirstName,
    altLastName,
    altRole,
    altEmail,
    altTelephone,
    altAddressLine1,
    altAddressLine2,
    altCounty,
    altPostcode,
    sharedSignedLink,
    prefContactMethod,
    prefCommunication,
    prefDataSharing,
    benAgeRange,
    benDob,
    benGen,
    benSex,
    benEthnicity,
    benReligion,
    benDisability,
    benDisabilityExtra,
    benMarital,
    benDependants,
    benPregnancy,
    numOfDependants,
    ageOfDependants,
    dependantInformation,
    currentAccom,
    benCurrentAccomLength,
    benHistOfHomelessness,
    benHistDetails,
    benTimeInNottingham,
    benLinktoNottingham,
    benLinkDetails,
    benGrantReason,
    grantDetails,
    benStory,
    grantAmountTotal,
    grantItemCost1,
    grantItemDetails1,
    grantItemCost2,
    grantItemDetails2,
    grantItemCost3,
    grantItemDetails3,
    grantItemCost4,
    grantItemDetails4,
    grantItemCost5,
    grantItemDetails5,
    grantQuoteLink,
    submissionDate,
  });

  return grant;
};

module.exports = mongoose.model("Grant", grantSchema);
