const Grant = require("../models/grantModel");
const mongoose = require("mongoose");

//get grants
const fetchGrants = async (req, res) => {
  const userId = req.auth._id;
  const grants = await Grant.find({ userId }).sort({ createdAt: -1 });
  res.status(200).json(grants);
};

//apply grants
const createGrant = async (req, res) => {
  const {
    benTitle,
    benFirstName,
    benLastName,
    benEmail,
    benTelephone,
    benAbode,
    benAddressLine1,
    benAddressLine2,
    benTown,
    altTitle,
    altFirstName,
    altLastName,
    altRole,
    altEmail,
    altTelephone,
    altAddressLine1,
    altAddressLine2,
    altCounty,
    altPostcode,
    sharedSignedLink,
    prefContactMethod,
    prefCommunication,
    prefDataSharing,
    benAgeRange,
    benDob,
    benGen,
    benSex,
    benEthnicity,
    benReligion,
    benDisability,
    benDisabilityExtra,
    benMarital,
    benDependants,
    benPregnancy,
    numOfDependants,
    ageOfDependants,
    dependantInformation,
    currentAccom,
    benCurrentAccomLength,
    benHistOfHomelessness,
    benHistDetails,
    benTimeInNottingham,
    benLinktoNottingham,
    benLinkDetails,
    benGrantReason,
    grantDetails,
    benStory,
    grantAmountTotal,
    grantItemCost1,
    grantItemDetails1,
    grantItemCost2,
    grantItemDetails2,
    grantItemCost3,
    grantItemDetails3,
    grantItemCost4,
    grantItemDetails4,
    grantItemCost5,
    grantItemDetails5,
    grantQuoteLink,
    submissionDate,
  } = req.body;
  try {
    const userId = req.auth._id;
    const grantStatus = "Pending";
    const grant = await Grant.applyGrant(
      userId,
      grantStatus,
      benTitle,
      benFirstName,
      benLastName,
      benEmail,
      benTelephone,
      benAbode,
      benAddressLine1,
      benAddressLine2,
      benTown,
      altTitle,
      altFirstName,
      altLastName,
      altRole,
      altEmail,
      altTelephone,
      altAddressLine1,
      altAddressLine2,
      altCounty,
      altPostcode,
      sharedSignedLink,
      prefContactMethod,
      prefCommunication,
      prefDataSharing,
      benAgeRange,
      benDob,
      benGen,
      benSex,
      benEthnicity,
      benReligion,
      benDisability,
      benDisabilityExtra,
      benMarital,
      benDependants,
      benPregnancy,
      numOfDependants,
      ageOfDependants,
      dependantInformation,
      currentAccom,
      benCurrentAccomLength,
      benHistOfHomelessness,
      benHistDetails,
      benTimeInNottingham,
      benLinktoNottingham,
      benLinkDetails,
      benGrantReason,
      grantDetails,
      benStory,
      grantAmountTotal,
      grantItemCost1,
      grantItemDetails1,
      grantItemCost2,
      grantItemDetails2,
      grantItemCost3,
      grantItemDetails3,
      grantItemCost4,
      grantItemDetails4,
      grantItemCost5,
      grantItemDetails5,
      grantQuoteLink,
      submissionDate
    );
    res.status(200).json({ grant });
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
};

module.exports = {
  fetchGrants,
  createGrant,
};
